# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb79570a707440530d222047587308d9691896d1bd5b5f8d053c7c4b9cef5cdf6d273c3451f4d54f6a3e1b81ff501ef29f469221861dc0cc50916670ba4906da

test:
  secret_key_base: 7516f6cebde31652729636ee8b6e69211a8b16edebf80d8541d4e1a71bda990c2673ffa2e3d8753427332abca07894f2199f3aa052f3e882725b5eb8bce20977

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
